# -*- mode: ruby -*-
# vi: set ft=ruby :

# Documentation to install nextcloud
# URL : https://thenewstack.io/deploy-the-latest-version-of-the-nextcloud-with-just-two-commands/

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  # Disable synced folder.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |v|
    v.name = "SCI6144-nextcloud"
  end

  config.vm.network "forwarded_port", guest: 80, host: 80, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1", id: "http-8080"
  config.vm.network "forwarded_port", guest: 8443, host: 8443, host_ip: "127.0.0.1", id: "https"
  
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
   end

  config.vm.provision "shell", inline: <<-SHELL

   apt-get update

   # Source: https://thenewstack.io/deploy-the-latest-version-of-the-nextcloud-with-just-two-commands/
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
   echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
   sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release -y
   sudo apt-get update
   sudo apt-get install docker-ce docker-ce-cli containerd.io -y
   sudo usermod -aG docker $USER

   # Launch
   docker run -d \
  --init \
  --sig-proxy=false \
  --name nextcloud-aio-mastercontainer \
  --restart always \
  --publish 80:80 \
  --publish 8080:8080 \
  --publish 8443:8443 \
  --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
  --volume /var/run/docker.sock:/var/run/docker.sock:ro \
  nextcloud/all-in-one:latest

  SHELL
end
