# -*- mode: ruby -*-
# vi: set ft=ruby :

# VM for BlueSpice
# BlueSpice URL : http://127.0.0.1
# BlueSpice install URL : http://127.0.0.1/
# BlueSpice admin username : admin
# BlueSpice admin password : sci6144-a20
# BlueSpice admin email : admin@localhost
# BlueSpice admin wiki name : SCI6144

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/ubuntu-20.04"

  # Disable synced folder.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "file", source: "C:/vm/BlueSpice/sources/", destination: "/tmp/"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |v|
    v.name = "SCI6144-BlueSpice"
  end

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
config.vm.network "forwarded_port", guest: 80, host: 80, host_ip: "127.0.0.1", id: "http"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "4096"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y apache2 libapache2-mod-php  mysql-server php7.4-gd php7.4-mbstring php7.4-gd php7.4-intl php7.4-mysql php7.4-xml unzip

     rm /var/www/html/index.html

     unzip /tmp/sources/BlueSpice-free-3.1.9.zip
     mv bluespice/* /var/www/html/
     chmod 775 -R /var/www/html
     chown www-data:www-data -R /var/www/html

     # Create database
     # This is not secure
     mysql -uroot -e "CREATE DATABASE bluespice"
     mysql -uroot -e "CREATE USER 'bluespice'@'localhost' IDENTIFIED BY 'pass'"
     mysql -uroot -e "GRANT ALL PRIVILEGES ON bluespice.* TO 'bluespice'@'localhost' WITH GRANT OPTION"

  SHELL
end
