# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile for OpenKM 6.3 - CE
# URL : 127.0.0.1:8080
# Admin username : okmAdmin
# Admin password : admin

# Documentation for dependencies : https://www.alfresco.com/fr/thank-you/thank-you-downloading-alfresco-community-edition-old-6.1

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu2004"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1", id: "tomcat"
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.

  config.vm.provision "shell", inline: <<-SHELL

    # See : https://docs.openkm.com/kcenter/view/okm-6.3-com/installing-on-ubuntu-and-debian.html
    
    # Create user named openkm
    adduser openkm

    # Increase ulimit in /etc/pam.d/su
    sed 's/^#session    required   pam_limits.so/session    required   pam_limits.so/' /etc/pam.d/su
  
    # Add these lines in /etc/security/limits.conf
    sed -i '55 a hard  nofile   6084' /etc/security/limits.conf
    sed -i '56 a soft  nofile   6084' /etc/security/limits.conf

    # Update and install Java 
    apt-get update
    apt-get install -y openjdk-8-jdk mysql-server clamav imagemagick ghostscript tesseract-ocr tesseract-ocr-fra
    apt-get install -y libreoffice --no-install-recommends  --no-install-suggests

    # Change MySQL root password
    # This is not secure
    /usr/bin/mysqladmin -u root -h localhost password 'password'

    # Create database
    # This is not secure
    CREATE DATABASE okmdb DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;
    CREATE USER openkm@localhost IDENTIFIED BY 'password';
    GRANT ALL ON okmdb.* TO openkm@localhost WITH GRANT OPTION;

    # Installing OpenKM and Tomcat bundle

    # Configuring Tomcat as a service
    cp /vagrant/sources/tomcat /etc/init.d/

    chmod 755 /etc/init.d/tomcat

    cd /home/openkm
    # Download the file. This may take to much time. We should have it locally
    wget https://cfhcable.dl.sourceforge.net/project/openkm/6.3.2/openkm-6.3.2-community-tomcat-bundle.zip
    unzip openkm-6.3.2-community-tomcat-bundle.zip

    # service tomcat start
    # This is not ok
    ./home/openkm/tomcat/bin/startup.sh

    SHELL

  config.vm.provision :shell, inline: "./home/openkm/tomcat/bin/startup.sh", run: 'always'
end