# -*- mode: ruby -*-
# vi: set ft=ruby :

# VM pour atom
# Open http://127.0.0.1
# The default admin login details are:
# Username: demo@example.com
# Password: demo

# Pour les étudiant.e.s. du cours ARV1055
# URL : http://127.0.0.1
# Informations de connexion :
# Nom d'usager : ebsi@example.com
# Mot de passe : ARV1055
# Rôle : contributeur

Vagrant.configure("2") do |config|

  config.vm.box = "artefactual/atom"

  # Disable synced folder. Pour éviter le message d'erreur au démarrage dans Virtualbox.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Nommage de la VM qui respecte notre modèle.
  config.vm.provider "virtualbox" do |v|
    v.name = "ARV1055-atom"
  end

  # Adresse de la VM qui respecte notre modèle.
  config.vm.network "forwarded_port", guest: 80, host: 80, host_ip: "127.0.0.1"

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
   end
end
