# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile for Odoo
# URL : http://127.0.0.1
# Instructions for deploying, see : https://www.odoo.com/documentation/13.0/setup/deploy.html
# URL for initial setup : http://127.0.0.1/web/database/selector
# Forwarding port 8069 to 80 may cause the website app not to work.
# Info for setup
# Database URL or IP : localhost
# Database name : 
# Database user : 
# Database password : 

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # The most common configuration options are documented and commented below.
    # For a complete reference, please see the online documentation at
    # https://docs.vagrantup.com.
  
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.box = "generic/ubuntu2004"
  
    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for updates when the user runs
    # `vagrant box outdated`. This is not recommended.
    # config.vm.box_check_update = false
  
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # NOTE: This will enable public access to the opened port
    # config.vm.network "forwarded_port", guest: 80, host: 8080
  
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine and only allow access
    # via 127.0.0.1 to disable public access
    # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    # See : https://www.odoo.com/fr_FR/forum/aide-1/question/url-for-odoo-application-157085
  config.vm.network "forwarded_port", guest: 80, host: 8069, host_ip: "127.0.0.1", id: "http"
  
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # config.vm.network "private_network", ip: "192.168.33.10"
  
    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    # config.vm.network "public_network"
  
    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # config.vm.synced_folder "../data", "/vagrant_data"
  
    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
      vb.memory = "4096"
    end
    #
    # View the documentation for the provider you are using for more
    # information on available options.
  
    # Enable provisioning with a shell script. Additional provisioners such as
    # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
    # documentation for more information about their specific syntax and use.
    config.vm.provision "shell", inline: <<-SHELL
  
      # Installation documentation, see : https://www.odoo.com/documentation/13.0/setup/install.html#packaged-installers
      # Install dependencies, see : https://www.odoo.com/documentation/13.0/setup/install.html#prepare
      apt-get update
      apt-get install -y build-essential postgresql
  
      # Set repository, see : https://www.odoo.com/documentation/13.0/setup/install.html#repository
      wget -O - https://nightly.odoo.com/odoo.key | apt-key add -
      echo "deb http://nightly.odoo.com/13.0/nightly/deb/ ./" >> /etc/apt/sources.list.d/odoo.list
      apt-get update
      apt-get install -y odoo
  
    SHELL
  end